In [1]:
# I - Data cleaning

In [2]:
# Check for duplicates and removing them

In [3]:
import pandas as pd

dflab2 = pd.read_csv('students.csv')

duplicates = dflab2.duplicated() # Boolean array 

# Number of duplicate rows
print(dflab2[duplicates]) 
print(f"Number of duplicate rows: {duplicates.sum()}")

      Name   Age  Gender  Score Grade  City
29  Rachid  22.0    Male   12.0     C  Oran
39    Lina  20.0  Female   18.0     A  Oran
Number of duplicate rows: 2

In [4]:
dflab2_cleaned = dflab2.drop_duplicates() # Dropping duplicates and storing cleaned dataframe into dflab2_cleaned
dflab2_cleaned

        Name   Age  Gender  Score Grade        City
0    Yasmine  20.0  Female   17.5     A   Boumerdes
1      Amine  21.0    Male   14.0     B     Algiers
2       Sara  19.0  Female   16.0     A  Tizi Ouzou
3      Karim  22.0    Male   11.5     C   Boumerdes
4       Lina  20.0  Female   18.0     A        Oran
5      Mehdi  23.0    Male    9.0     D     Algiers
6       Nour  18.0  Female   15.5     B       Setif
7      Ilyes  21.0    Male   13.0     B   Boumerdes
8     Meriem  20.0  Female   16.5     A     Tlemcen
9      Walid  24.0    Male   10.0     C        Oran
10      Ines  19.0  Female   14.5     B     Algiers
11     Rayan  22.0    Male   12.0     C       Setif
12      Amel  21.0  Female   17.0     A   Boumerdes
13     Samir  20.0    Male    8.5     D  Tizi Ouzou
14     Lamia  19.0  Female   15.0     B        Oran
15      Adel  23.0    Male   13.5     B     Algiers
16     Kenza  20.0  Female   18.5     A       Setif
17     Bilal  21.0    Male   11.0     C   Boumerdes
18     Rania  22.0  Female   16.0     A     Tlemcen
19      Omar  19.0    Male   14.0     B        Oran
20    Yacine  -5.0    Male   12.5     C     Algiers
21     Dalia  20.0  Female    NaN     B   Boumerdes
22    Hichem   NaN    Male   13.0     B       Setif
23     Nadia  21.0     NaN   17.0     A        Oran
24     Fares  22.0    Male   10.5   NaN     Algiers
25     Sofia  19.0  Female   15.0     B         NaN
26      Anis  20.0       M   14.0     B     algiers
27      Maya  21.0  female   16.0     A   Boumerdes
28    Rachid  22.0    Male   12.0     C        Oran
30      Lyes  25.0    Male    7.0     D     Tlemcen
31     Mouna  18.0  Female   19.0     A       Setif
32      Said  20.0    Male   13.5     B   Boumerdes
33     Farah  19.0  Female   16.5     A     Algiers
34     Nabil  21.0    Male   11.5     C  Tizi Ouzou
35     Amina  20.0  Female   15.0     B        Oran
36  Zinedine  22.0    Male    9.5     D       Setif
37  Chahinez  19.0  Female   17.5     A   Boumerdes
38    Mourad  21.0    Male   14.5     B     Tlemcen

In [5]:
# Number of duplicate rows 
print(f"Number of duplicate rows: {dflab2_cleaned.duplicated().sum()}")

Number of duplicate rows: 0

In [6]:
# Dropping duplicates directly from the initial dataframe
dflab2.drop_duplicates(inplace=True)
dflab2

        Name   Age  Gender  Score Grade        City
0    Yasmine  20.0  Female   17.5     A   Boumerdes
1      Amine  21.0    Male   14.0     B     Algiers
2       Sara  19.0  Female   16.0     A  Tizi Ouzou
3      Karim  22.0    Male   11.5     C   Boumerdes
4       Lina  20.0  Female   18.0     A        Oran
5      Mehdi  23.0    Male    9.0     D     Algiers
6       Nour  18.0  Female   15.5     B       Setif
7      Ilyes  21.0    Male   13.0     B   Boumerdes
8     Meriem  20.0  Female   16.5     A     Tlemcen
9      Walid  24.0    Male   10.0     C        Oran
10      Ines  19.0  Female   14.5     B     Algiers
11     Rayan  22.0    Male   12.0     C       Setif
12      Amel  21.0  Female   17.0     A   Boumerdes
13     Samir  20.0    Male    8.5     D  Tizi Ouzou
14     Lamia  19.0  Female   15.0     B        Oran
15      Adel  23.0    Male   13.5     B     Algiers
16     Kenza  20.0  Female   18.5     A       Setif
17     Bilal  21.0    Male   11.0     C   Boumerdes
18     Rania  22.0  Female   16.0     A     Tlemcen
19      Omar  19.0    Male   14.0     B        Oran
20    Yacine  -5.0    Male   12.5     C     Algiers
21     Dalia  20.0  Female    NaN     B   Boumerdes
22    Hichem   NaN    Male   13.0     B       Setif
23     Nadia  21.0     NaN   17.0     A        Oran
24     Fares  22.0    Male   10.5   NaN     Algiers
25     Sofia  19.0  Female   15.0     B         NaN
26      Anis  20.0       M   14.0     B     algiers
27      Maya  21.0  female   16.0     A   Boumerdes
28    Rachid  22.0    Male   12.0     C        Oran
30      Lyes  25.0    Male    7.0     D     Tlemcen
31     Mouna  18.0  Female   19.0     A       Setif
32      Said  20.0    Male   13.5     B   Boumerdes
33     Farah  19.0  Female   16.5     A     Algiers
34     Nabil  21.0    Male   11.5     C  Tizi Ouzou
35     Amina  20.0  Female   15.0     B        Oran
36  Zinedine  22.0    Male    9.5     D       Setif
37  Chahinez  19.0  Female   17.5     A   Boumerdes
38    Mourad  21.0    Male   14.5     B     Tlemcen

In [7]:
# Number of duplicate rows 
print(f"Number of duplicate rows: {dflab2.duplicated().sum()}")

Number of duplicate rows: 0

In [8]:
# Checking for missing data and processing them

In [9]:
missing_values = dflab2.isnull().sum() 
print(missing_values)

Name      0
Age       1
Gender    1
Score     1
Grade     1
City      1
dtype: int64

In [10]:
# Handling missing data

In [11]:
# Remove missing data:
dflab2= dflab2.dropna() 
print(dflab2.isnull().sum())

Name      0
Age       0
Gender    0
Score     0
Grade     0
City      0
dtype: int64

In [13]:
# Imputation
dflab2['Score'] = dflab2['Score'].fillna(dflab2['Score'].mean())
print(dflab2.isnull().sum())

Name      0
Age       0
Gender    0
Score     0
Grade     0
City      0
dtype: int64

/tmp/ipykernel_1730/2067635626.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflab2['Score'] = dflab2['Score'].fillna(dflab2['Score'].mean())

In [14]:
# II - Data normalization

In [15]:
from sklearn.preprocessing import MinMaxScaler 

scaler = MinMaxScaler() 
dflab2['Age'] = scaler.fit_transform(dflab2[['Age']]) 

print(dflab2)

        Name       Age  Gender  Score Grade        City
0    Yasmine  0.833333  Female   17.5     A   Boumerdes
1      Amine  0.866667    Male   14.0     B     Algiers
2       Sara  0.800000  Female   16.0     A  Tizi Ouzou
3      Karim  0.900000    Male   11.5     C   Boumerdes
4       Lina  0.833333  Female   18.0     A        Oran
5      Mehdi  0.933333    Male    9.0     D     Algiers
6       Nour  0.766667  Female   15.5     B       Setif
7      Ilyes  0.866667    Male   13.0     B   Boumerdes
8     Meriem  0.833333  Female   16.5     A     Tlemcen
9      Walid  0.966667    Male   10.0     C        Oran
10      Ines  0.800000  Female   14.5     B     Algiers
11     Rayan  0.900000    Male   12.0     C       Setif
12      Amel  0.866667  Female   17.0     A   Boumerdes
13     Samir  0.833333    Male    8.5     D  Tizi Ouzou
14     Lamia  0.800000  Female   15.0     B        Oran
15      Adel  0.933333    Male   13.5     B     Algiers
16     Kenza  0.833333  Female   18.5     A       Setif
17     Bilal  0.866667    Male   11.0     C   Boumerdes
18     Rania  0.900000  Female   16.0     A     Tlemcen
19      Omar  0.800000    Male   14.0     B        Oran
20    Yacine  0.000000    Male   12.5     C     Algiers
26      Anis  0.833333       M   14.0     B     algiers
27      Maya  0.866667  female   16.0     A   Boumerdes
28    Rachid  0.900000    Male   12.0     C        Oran
30      Lyes  1.000000    Male    7.0     D     Tlemcen
31     Mouna  0.766667  Female   19.0     A       Setif
32      Said  0.833333    Male   13.5     B   Boumerdes
33     Farah  0.800000  Female   16.5     A     Algiers
34     Nabil  0.866667    Male   11.5     C  Tizi Ouzou
35     Amina  0.833333  Female   15.0     B        Oran
36  Zinedine  0.900000    Male    9.5     D       Setif
37  Chahinez  0.800000  Female   17.5     A   Boumerdes
38    Mourad  0.866667    Male   14.5     B     Tlemcen

/tmp/ipykernel_1730/3748303048.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflab2['Age'] = scaler.fit_transform(dflab2[['Age']])

In [16]:
# III - Data encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
# Label Encoding
encoder = LabelEncoder() 
dflab2['Gender'] = encoder.fit_transform(dflab2['Gender']) 

print(dflab2.head())

      Name       Age  Gender  Score Grade        City
0  Yasmine  0.833333       0   17.5     A   Boumerdes
1    Amine  0.866667       2   14.0     B     Algiers
2     Sara  0.800000       0   16.0     A  Tizi Ouzou
3    Karim  0.900000       2   11.5     C   Boumerdes
4     Lina  0.833333       0   18.0     A        Oran

/tmp/ipykernel_1730/2411913145.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dflab2['Gender'] = encoder.fit_transform(dflab2['Gender'])

In [19]:
# One-Hot Encoding
df_one_hot = pd.get_dummies(dflab2, columns=['City'], drop_first=True) 
print(df_one_hot)

        Name       Age  Gender  Score Grade  City_Boumerdes  City_Oran  \
0    Yasmine  0.833333       0   17.5     A            True      False
1      Amine  0.866667       2   14.0     B           False      False
2       Sara  0.800000       0   16.0     A           False      False
3      Karim  0.900000       2   11.5     C            True      False
4       Lina  0.833333       0   18.0     A           False       True
5      Mehdi  0.933333       2    9.0     D           False      False
6       Nour  0.766667       0   15.5     B           False      False
7      Ilyes  0.866667       2   13.0     B            True      False
8     Meriem  0.833333       0   16.5     A           False      False
9      Walid  0.966667       2   10.0     C           False       True
10      Ines  0.800000       0   14.5     B           False      False
11     Rayan  0.900000       2   12.0     C           False      False
12      Amel  0.866667       0   17.0     A            True      False
13     Samir  0.833333       2    8.5     D           False      False
14     Lamia  0.800000       0   15.0     B           False       True
15      Adel  0.933333       2   13.5     B           False      False
16     Kenza  0.833333       0   18.5     A           False      False
17     Bilal  0.866667       2   11.0     C            True      False
18     Rania  0.900000       0   16.0     A           False      False
19      Omar  0.800000       2   14.0     B           False       True
20    Yacine  0.000000       2   12.5     C           False      False
26      Anis  0.833333       1   14.0     B           False      False
27      Maya  0.866667       3   16.0     A            True      False
28    Rachid  0.900000       2   12.0     C           False       True
30      Lyes  1.000000       2    7.0     D           False      False
31     Mouna  0.766667       0   19.0     A           False      False
32      Said  0.833333       2   13.5     B            True      False
33     Farah  0.800000       0   16.5     A           False      False
34     Nabil  0.866667       2   11.5     C           False      False
35     Amina  0.833333       0   15.0     B           False       True
36  Zinedine  0.900000       2    9.5     D           False      False
37  Chahinez  0.800000       0   17.5     A            True      False
38    Mourad  0.866667       2   14.5     B           False      False

    City_Setif  City_Tizi Ouzou  City_Tlemcen  City_algiers
0        False            False         False         False
1        False            False         False         False
2        False             True         False         False
3        False            False         False         False
4        False            False         False         False
5        False            False         False         False
6         True            False         False         False
7        False            False         False         False
8        False            False          True         False
9        False            False         False         False
10       False            False         False         False
11        True            False         False         False
12       False            False         False         False
13       False             True         False         False
14       False            False         False         False
15       False            False         False         False
16        True            False         False         False
17       False            False         False         False
18       False            False          True         False
19       False            False         False         False
20       False            False         False         False
26       False            False         False          True
27       False            False         False         False
28       False            False         False         False
30       False            False          True         False
31        True            False         False         False
32       False            False         False         False
33       False            False         False         False
34       False             True         False         False
35       False            False         False         False
36        True            False         False         False
37       False            False         False         False
38       False            False          True         False